#!/bin/bash
############################
# This script downloads and sets up an environment
############################
set -x

export ARTIFACTS_DIR="$HOME/setup_artifacts"

echo "Creating $ARTIFACTS_DIR"
mkdir -p "$ARTIFACTS_DIR"

# Prevent apt from bothering me about restarting daemons
sudo sed -i "s/^#\$nrconf{restart} = 'i';/\$nrconf{restart} = 'a';/" /etc/needrestart/needrestart.conf

# Order is (somewhat) important
bash src/install_essentials
# This has *probably* already been run
#bash "src/install_git"
bash src/install_zsh
bash src/install_fzf
bash src/install_fd
bash src/remap_capslock
bash src/install_node
bash src/install_diff_so_fancy
bash src/link_dotfiles
bash src/install_vim

git submodule update --init --recursive

echo "========== COMPLETE =========="
echo "Artifacts from setup process are stored in $ARTIFACTS_DIR."

set +x
# vim:foldmethod=marker:foldlevel=0:foldmarker====[,===]
