# vim:ft=kitty

# Fonts
font_family Monofur Nerd Font Mono
font_size 12

# Window
window_padding_width 0 0 0 0
hide_window_decorations yes

# Ctrl and click to open a link
mouse_map ctrl+left press ungrabbed,grabbed mouse_click_url

# Animated cursor
cursor_trail 3

include themes/dark.conf
include ~/.local/state/dotfiles/theme/kitty.conf
