# If not running interactively, don't do anything
case $- in
    *i*) ;;
    *) return;;
esac

# My custom functions
[[ -f "$HOME/.funcs" ]] && source "$HOME/.funcs"

#===[ history
# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
# append to the history file, don't overwrite it
shopt -s histappend
# max number of lines in the history file
HISTFILESIZE=20000000
# the number of commands to "remember"
HISTSIZE=10000000
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
#===]
#===[ colors
# enable color support of ls and grep
if [ -x /usr/bin/dircolors ]; then
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colors for man
export LESS_TERMCAP_mb=$'\e[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\e[1;33m'     # begin blink
export LESS_TERMCAP_so=$'\e[01;44;37m' # begin reverse video
export LESS_TERMCAP_us=$'\e[01;37m'    # begin underline
export LESS_TERMCAP_me=$'\e[0m'        # reset bold/blink
export LESS_TERMCAP_se=$'\e[0m'        # reset reverse video
export LESS_TERMCAP_ue=$'\e[0m'        # reset underline
export MANPAGER='less -s -M +Gg'       # percentage into the document
#===]
#===[ aliases
if [ -f ~/.sh_aliases ]; then
    source ~/.sh_aliases
fi
#===]
#===[ path
# initialize PATH
PATH=/usr/local/bin:/bin:/usr/bin:/usr/sbin:/sbin

if [ "$TERM" != "tmux-256color" ]; then
	export TERM=xterm-256color
fi
prepend "$HOME/.local/bin"
prepend "$HOME/bin"

export PATH
#===]
#===[ editor
# use a *real* editor
export VISUAL=vim
export EDITOR="$VISUAL"
# turn on vi-mode
set -o vi
#===]
#===[ unsorted
# Bash completion
if [ -f /usr/share/bash-completion/bash_completion ]; then
. /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
. /etc/bash_completion
fi

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# extended globbing for things like !(dont_match_me)
shopt -s extglob

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

xtitle $PWD

set -o notify           # Notify immediately if job changes state
shopt -s checkjobs      # lists the status of any stopped and running jobs before exiting

shopt -s no_empty_cmd_completion

# light spellcheck on cd
shopt -s cdspell

# This is kind of goofy. To check for interactive logins, you generally test the
# value of PS1 -- therefore, I need to set this at the very end, just in case..
if [ "$PS1" ]; then
    fastprompt
fi

# fzf settings
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
#===]

[[ -f "$HOME/.dotfiles/localrc" ]] && source $HOME/.dotfiles/localrc

# vim:foldmethod=marker:foldlevel=0:foldmarker====[,===]
