#!/bash

pycalc() {
  python3 << EOF
from math import *
from datetime import *
print($*)
EOF
}

# Opposite of cd. Giving an argument jumps up that many directories
bd() {
  iter="${1:-1}"
  while [[ "$iter" -gt 0 ]]
  do
      (( iter = iter - 1 ))
      cd ..
  done
}

# Generate a random password
randpw() {
  < /dev/urandom tr -dc A-Z-a-z-0-9%\!+@^ | head -c"${1:-32}"
  echo
}

# List all todos
todo() {
  grep --color=always -HInsr "TODO" ./* | awk '{printf $1; for (i=2; i <= NF; i++) printf FS$i; print NL }'
}

# Scrollable, colored grep
grepc() {
  grep -I "$@" --color=always | less -R --quit-if-one-screen
}

# Scrollable, colored ag
agc() {
  ag --color --group "$@" | less -R --quit-if-one-screen
}

count() {
  ag "$@" -c | awk '
    BEGIN {sum = 0; FS=":"}
      {printf "%-10d %s\n", $2, $1}
      {sum = sum + $2}
    END {printf "--------------------------------------------------------------------------------\n%-10d Total\n", sum}
    '
}

# Colorful trees
treec() {
  tree -C "$@" | less -R --quit-if-one-screen
}

# Fast access to virtual python environments
vpy() {
  if [ -z "$1" ]; then
    echo "Need to provide a venv"
  elif [ "$1" = "ls" ]; then
    ls "$HOME/.venvs"
  else
    source "$HOME/.venvs/$1/bin/activate"
  fi
}

# Paste to ix.io
ix() {
  # examples: ix < file; command | ix
  curl -n -F 'f:1=<-' http://ix.io;
}

# Setup local branches to track all remote branches
# Note: This will not overwrite any local branch. This means that if there is a
# name collision between a local branch and a remote branch, this command will
# fail for that branch
gpa() {
  git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
}

# Create a temporary directory, then go there.
# If an argument was provided, use it as a suffix
tmp() {
  suffix=
  if [[ -n "$1" ]]; then
    suffix="-$1"
  fi
  cd "$(mktemp -d --suffix="$suffix")"
}

# Like more, but side by side files
smore() {
  pr -m -T -s\| -W"$COLUMNS" "$@" | less -R --quit-if-one-screen
}

# Takes a list of files/directories "foo", and creates copies called "foo.bak"
bak() {
  for item in "$@"; do
    if [[ -e "$item" ]]; then
      printf "copying %s to %s.bak\n" "$item" "$item"
      cp -r "$item" "$item.bak"
    else
      printf "warning: file or directory \"%s\" could not be found - skipping\n" "$item"
    fi
  done
}

# Wraps an interactive shell with readline. Requires rlwrap
rl() {
  if ! command -v rlwrap; then
    printf "Couldn't find rlwrap, please install it\n"
  fi
  if (( $# != 1 )); then
    printf "Usage: %s <wrapped_application>\n" "$0"
    printf "EXAMPLE: %s python\n" "$0"
    return
  fi
  rlwrap --remember --complete-filenames "$1"
}

# convenience routine which appends a string to a path.
append() {
  if (( $# != 1 )); then
    printf "Usage: %s <absolute_path>\n" "$0"
    printf "EXAMPLE: %s %s/bin\n" "$0" "$HOME"
    return
  fi
  addpath "$1" append
}

# convenience routine which prepends a string to a path.
prepend() {
  if (( $# != 1 )); then
    printf "Usage: %s <absolute_path>\n" "$0"
    printf "EXAMPLE: %s %s/bin\n" "$0" "$HOME"
    return
  fi
  addpath "$1" prepend
}

#===[ addpath
# Add $1 to the PATH variable.  $2 must be "append" or "prepend" to indicate
# where the component is added.
addpath()
{
  # Don't add directory if it doesn't exist...
  if [ ! -d "$1" ]; then
    echo "$1 is not a directory"
    return
  fi

  value="$PATH"
  case "$value" in
    *:"$1":*|*:"$1"|"$1":*|"$1")  # if the directory is already in the path
      result="$value"  # use the old path
      ;;
    "")  # if the path is empty
      result="$1"  # use the directory (as the first item)
      ;;
    *)  #otherwise...
      case "$2" in
        p*)  # if it looks like "prepend"
          result="$1:$value"  # add the directory to the front
          ;;
        *)  # otherwise
          result="$value:$1"  # add the directory to the back
          ;;
      esac
  esac

  export PATH="$result"
  unset result value
}
#===]
# vim:foldmethod=marker:foldlevel=0:foldmarker====[,===]
