export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin":/home/ian/.config/agency/CurrentVersion

# Add go to the environment
export GOROOT="/usr/local/go"
export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
export PATH=$GOROOT/bin:$PATH
export PATH=$GOBIN:$PATH

# Start the ssh agent if it isn't already running
if [ -z "$SSH_AUTH_SOCK" ]; then
  eval $(ssh-agent)
  # Add any keys
  ssh-add
fi

# Use nvim as the pager for man
export MANPAGER='nvim +Man!'

# vim: ft=sh
