#!/usr/bin/zsh

source "$HOME/.dotfiles/links/zsh/utils/utils.sh"
source "$HOME/.dotfiles/links/zsh/aliases.zsh"
source "$HOME/.dotfiles/links/zsh/functions/functions.sh"
source "$HOME/.dotfiles/links/zsh/keybinds.zsh"
# NOTE: This MUST be sourced before autosuggestions (which is near the bottom of this file at time of writing)
source "$HOME/.dotfiles/links/zsh/completion.zsh"

# Turn on colors
autoload -U colors && colors

#===[ History
# TODO: clean this up too
# History file configuration
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000

## History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt inc_append_history     # add commands to HISTFILE in order of execution

#===[ fzf
source ~/.fzf.zsh

export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --filepath-word" # Note to self: --border doesn't play nicely with fzf-tab
export FZF_DEFAULT_COMMAND="fd --type file --hidden --no-ignore --exclude='.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# Preview file content using bat (https://github.com/sharkdp/bat)
export FZF_CTRL_T_OPTS="
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"
export FZF_ALT_C_COMMAND="fd --type d --hidden --no-ignore --exclude='.git'"
# Print tree structure in the preview window
export FZF_ALT_C_OPTS="--preview 'tree -C {}'"

#===[ Path extensions
prepend "$HOME/.dotfiles/links/bin"
prepend "$HOME/.local/bin"
prepend "/mnt/c/Users/ianhowell/AppData/Local/Programs/Microsoft VS Code/bin"

# Add go to the environment
export GOROOT="/usr/local/go"
export PATH=$GOROOT/bin:$PATH
export PATH=$HOME/go/bin:$PATH

#===[ Unsorted
# Allow proper substitution in the prompt
setopt PROMPT_SUBST

# Setup default editor
export EDITOR='nvim'
export VISUAL='nvim'

# Don't share a history between shells. That's weird.
unsetopt share_history
setopt no_share_history

# recognize that comments are comments
setopt interactivecomments

# Source work-specific zshrc (if it exists)
if [[ -s "$HOME/.config/work/zshrc" ]]; then
    source "$HOME/.config/work/zshrc"
fi

# Set up zoxide
eval "$(zoxide init --cmd cd zsh)"

source "$HOME/.dotfiles/links/zsh/prompt.zsh"

#===[ Plugins

source "$HOME/.dotfiles/links/zsh/fzf-git.sh/fzf-git.sh"

# Fish-like autosuggestions
bindkey '^y' autosuggest-accept
bindkey '^e' autosuggest-clear
source "$HOME/.dotfiles/links/zsh/zsh-autosuggestions.zsh"

source "$HOME/.dotfiles/links/zsh/almostontop.plugin.zsh"
