# WORK IN PROGRESS
# # Turn on convenient colors
# autoload -U colors && colors

# # Allow proper substitution in the prompt
# setopt PROMPT_SUBST

# # Outputs current branch info in prompt format
# function git_prompt_info() {
#   local ref
#   ref=$(command git symbolic-ref HEAD 2> /dev/null) || \
#   ref=$(command git rev-parse --short HEAD 2> /dev/null) || return 0
#   local prefix suffix
#   prefix="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
#   suffix="%{$reset_color%} "
#   echo "$prefix${ref#refs/heads/}$(parse_git_dirty)$suffix"
# }

# # Checks if working tree is dirty
# function parse_git_dirty() {
#   local STATUS=''
#   local -a FLAGS
#   local dirty clean
#   dirty="%{$fg[blue]%}) %{$fg[yellow]%}✗"
#   clean="%{$fg[blue]%})"
#   FLAGS=('--porcelain')
#   FLAGS+='--ignore-submodules=dirty'
#   STATUS=$(command git status ${FLAGS} 2> /dev/null | tail -n1)
#   if [[ -n $STATUS ]]; then
#     echo "$dirty"
#   else
#     echo "$clean"
#   fi
# }


# ret_status="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
# PROMPT='${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'

export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(
  git
  vi-mode
)
source $ZSH/oh-my-zsh.sh

source ~/.sh_aliases

# Command mode indicator for vi-mode
MODE_INDICATOR="%{$fg_bold[magenta]%}(cmd)%{$reset_color%}"
# Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
export KEYTIMEOUT=1

# zsh's backword menu complete is different from readline's for some reason
bindkey '^[[Z' reverse-menu-complete

# Setup default editor
export EDITOR='vim'
export VISUAL='vim'

# My personal bin
[[ -d $HOME/bin ]] && export PATH="$HOME/bin:$PATH"

# My custom functions
[[ -f $HOME/.funcs ]] && source $HOME/.funcs

# colors for man
export LESS_TERMCAP_mb=$'\e[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\e[1;33m'     # begin blink
export LESS_TERMCAP_so=$'\e[01;44;37m' # begin reverse video
export LESS_TERMCAP_us=$'\e[01;37m'    # begin underline
export LESS_TERMCAP_me=$'\e[0m'        # reset bold/blink
export LESS_TERMCAP_se=$'\e[0m'        # reset reverse video
export LESS_TERMCAP_ue=$'\e[0m'        # reset underline
export MANPAGER='less -s -M +Gg'       # percentage into the document

unsetopt share_history
setopt no_share_history

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPS="--extended"
export FZF_DEFAULT_COMMAND="fd --type f"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

[[ -f "$HOME/.dotfiles/localrc" ]] && source $HOME/.dotfiles/localrc

fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    fg
  else
    bg
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

type helm > /dev/null && source <(helm completion zsh)
type kubectl > /dev/null && source <(kubectl completion zsh)
