#!/bin/bash
set -x

echo "Setting up Vim"

ARTIFACTS_DIR="${ARTIFACTS_DIR:-$(mktemp -d)}"

install_vim()
{
  vim_exists=$(command -v vim)
  if [ -n "$vim_exists" ]; then
      # Vim exists. Remove it
      sudo apt-get -qq remove vim vim-runtime gvim
  fi

  # Install make, gcc, and curses. These are dependencies
  sudo apt-get install -y -q make gcc libncurses5-dev

  # Install required X libraries - these are needed for clipboard support
  sudo apt-get install -y -q libx11-dev libxtst-dev libxt-dev libsm-dev libxpm-dev

  # Download, configure, build, and install
  tag=$(curl -s https://github.com/vim/vim/tags| \
    awk 'BEGIN {FS="/"} /\/vim\/vim\/archive\/.*tar.*/ {print $7}' | \
    sort -r | \
    head -n1 | \
    cut -f1 -d\"
  )
  dirname="$ARTIFACTS_DIR/vim"
  mkdir -p "$dirname"
  tarfile="$dirname/$tag"
  curl -L "https://github.com/vim/vim/archive/$tag" -o "$tarfile"
  tar -zxf "$tarfile" -C "$dirname" --strip-components 1
  cd "$dirname" || (echo "Couldn't cd to directory [$dirname]"; exit)

  ./configure --with-features=huge \
              --enable-multibyte \
              --enable-rubyinterp=yes \
              --enable-python3interp=yes \
              --enable-perlinterp=yes \
              --enable-luainterp=yes \
              --enable-cscope \
              --with-x=yes \
              --disable-gui \
              --prefix=/usr/local
  sudo make install >/dev/null

  vim +PlugInstall +qall
}

# Use a subshell so that we don't need to remember where we started
(
  install_vim
)

set +x
