#!/bin/bash
set -x

echo "================================================================================"
echo "| Installing fd                                                                 "
echo "================================================================================"

ARTIFACTS_DIR="${ARTIFACTS_DIR:-$(mktemp -d)}"

install_fd() {
  wget https://github.com/sharkdp/fd/releases/download/v7.2.0/fd-musl_7.2.0_amd64.deb \
    -O "$ARTIFACTS_DIR/fd-musl_7.2.0_amd64.deb"
  sudo dpkg -i "$ARTIFACTS_DIR/fd-musl_7.2.0_amd64.deb"
}

# Use a subshell so that we don't need to remember where we started
(
  install_fd
)

set +x
