#!/bin/bash

if [[ ! -d $HOME/bin ]]; then
    mkdir "$HOME/bin"
fi

if [[ ! -f $HOME/bin/delta ]]; then
    echo "Downloading delta..."
    tmpdir=$(mktemp -d)
    wget -O "$tmpdir/delta.tar.gz" https://github.com/dandavison/delta/releases/download/0.18.1/delta-0.18.1-x86_64-unknown-linux-gnu.tar.gz
    tar -xzf "$tmpdir/delta.tar.gz" -C "$tmpdir"
    mv "$tmpdir/delta-0.18.1-x86_64-unknown-linux-gnu/delta" "$HOME/bin"
fi
