#!/bin/bash

ARTIFACTS_DIR="${ARTIFACTS_DIR:-$(mktemp -d)}"

function main() {
  if is_installed; then
    return
  fi

  print_banner
  install_node
}

function is_installed() {
  command -v node >/dev/null
}

function print_banner() {
  echo "================================================================================"
  echo "| Installing node                                                              |"
  echo "================================================================================"
}

function install_node() {
  curl -fsSL https://deb.nodesource.com/setup_23.x -o "$ARTIFACTS_DIR/nodesource_setup.sh"
  sudo -E bash "$ARTIFACTS_DIR/nodesource_setup.sh"
  sudo apt-get install -y nodejs
}

main
