#!/bin/bash

ARTIFACTS_DIR="${ARTIFACTS_DIR:-$(mktemp -d)}"

install_dependencies() {
  sudo apt-get install -y ninja-build gettext cmake unzip curl build-essential
}

install_plugins() {
  vim +PlugInstall +qall
}

install_neovim() {
  cd "$ARTIFACTS_DIR" || return

  install_dependencies

  git clone https://github.com/neovim/neovim
  cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
  sudo make install

  install_plugins
}

echo "################################################################################"
echo "#                              Setting up Neovim                               #"
echo "################################################################################"

install_neovim
