#!/bin/bash

echo "================================================================================"
echo "| Installing kitty                                                                             |"
echo "================================================================================"

curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin \
    installer=nightly launch=n
