#!/bin/bash
set -x

install_zsh() {
  zsh_exists=$(command -v zsh)
  if [ -z "$zsh_exists" ]; then
      sudo apt-get -qq -y install zsh
  fi

  # If this user's login shell is not already "zsh", attempt to switch.
  TEST_CURRENT_SHELL=$(basename "$SHELL")
  if [ "$TEST_CURRENT_SHELL" != "zsh" ]; then
    if hash chsh >/dev/null 2>&1; then
      echo "Time to change your default shell to zsh!"
      chsh -s $(grep /zsh$ /etc/shells | tail -1)
    else
      # This is a hack...
      bash_loc=$(which bash)
      zsh_loc=$(which zsh)
      sudo sed -i -e "s,$HOME:$bash_loc,$HOME:$zsh_loc," /etc/passwd
    fi
  fi
  echo 'zsh installed :)'
}

(
  install_zsh
)

set +x
