#!/bin/bash

main() {
  delete_go
  install_go
}

delete_go() {
  sudo rm -rf /usr/local/go
}

install_go() {
  print_banner "Installing go"

  tmpdir=$(mktemp -d)
  trap 'rm -rf "$tmpdir"' EXIT

  filename=$(
    curl -sL 'https://golang.org/dl/?mode=json' |
      jq '.[0].files[] | select(.arch == "amd64") | select(.os == "linux") | .filename' -r
  )

  tarball="$tmpdir/$filename"
  release_url="https://go.dev/dl/$filename"
  # Download and install
  curl -sL "$release_url" --output "$tarball"
  sudo tar -C /usr/local -xzf "$tarball"
}

function print_banner() {
  echo "================================================================================"
  echo "$1"
  echo "================================================================================"
}

main
