#!/bin/bash
set -x

echo "Setting up Vim"

ARTIFACTS_DIR="${ARTIFACTS_DIR:-$(mktemp -d)}"

install_vim()
{
  vim_exists=$(command -v vim)
  if [ ! -z "$vim_exists" ]; then
      # Vim exists. Remove it
      sudo apt-get -qq remove vim vim-runtime gvim
  fi

  # Download, configure, build, and install
  release=$(curl -s https://github.com/vim/vim/releases| \
    awk 'BEGIN {FS="/"} /\/vim\/vim\/archive\/.*tar.*/ {print $5}' | \
    sort -r | \
    head -n1 | \
    cut -f1 -d\"
  )
  dirname="$ARTIFACTS_DIR/vim"
  mkdir -p "$dirname"
  tarfile="$dirname/$release"
  curl -L "https://github.com/vim/vim/archive/$release" -o "$tarfile"
  tar -zxf "$tarfile" -C "$dirname" --strip-components 1
  cd "$dirname" || (echo "Couldn't cd to directory [$dirname]"; exit)

  ./configure --with-features=huge \
              --enable-multibyte \
              --enable-rubyinterp=yes \
              --enable-python3interp=yes \
              --with-python3-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu \
              --enable-perlinterp=yes \
              --enable-luainterp=yes \
              --enable-gui=gtk2 \
              --enable-cscope \
              --prefix=/usr/local
  sudo make install

  vim +PlugInstall +qall
}

# Use a subshell so that we don't need to remember where we started
(
  install_vim
)

set +x
