#!/bin/bash
set -x

echo "Setting up essentials"
sudo apt-get -y update

# The following are library-type things. They're basically dependencies
sudo apt-get install -y \
  libncurses5-dev \
  libgtk2.0-dev \
  libatk1.0-dev \
  libcairo2-dev \
  libx11-dev \
  libxpm-dev \
  libxt-dev \
  python-dev \
  python3-dev \
  ruby-dev \
  lua5.1 \
  lua5.1-dev \
  libperl-dev \
  ;

# These are my programs
sudo apt-get install -y \
  curl \
  git \
  make \
  silversearcher-ag \
  tmux \
  tree \
  xclip \
  shellcheck \
  bat \
  ;

sudo ln -s /usr/bin/batcat /usr/bin/bat

set +x
