#!/bin/bash
set -x

sudo add-apt-repository -y ppa:aos1/diff-so-fancy

# Copilot claims that I can specify the release name in the sources.list.d file, which will prevent the need
# to run a full apt-get update.
# sudo apt-get update -y
sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/aos1-ubuntu-diff-so-fancy-$(lsb_release -cs).list" -y

sudo apt-get install -y diff-so-fancy

set +x
