#!/bin/bash

main() {
  if command -v fdfind; then
    return
  fi

  print_banner
  install
  link_binary
}

install() {
  sudo apt install fd-find
}

link_binary() {
  ln -s $(which fdfind) ~/.local/bin/fd
}

print_banner() {
  echo "================================================================================"
  echo "$1"
  echo "================================================================================"
}

main
