#!/bin/bash

links_dir=$HOME/.dotfiles/links

# the format here is
# src:target
# where "src" is rooted in $links_dir, and "target" is rooted in $HOME"
links="
bashrc:.bashrc
bin:.bin
funcs:.funcs
gitconfig:.gitconfig
global_gitignore:.global_gitignore
inputrc:.inputrc
zprofile:.zprofile
sh_aliases:.sh_aliases
tmux.conf:.tmux.conf
vim:.vim
vimrc:.vimrc
zsh:.zsh
zshenv:.zshenv
zshrc:.zshrc
git-hook-post-commit:.dotfiles/.git/hooks/post-commit
git-hook-post-commit:.dotfiles/.git/hooks/post-rewrite
"

for link in $links; do
  # split the links into src and target
  src="$links_dir/${link%:*}"
  target="$HOME/${link#*:}"

  # ensure that the target directory exists
  target_dir="${target%/*}"
  mkdir -p "$target_dir"

  # delete any old files/links
  if [[ -e "$target" || -h "$target" ]]; then
    rm "$target"
  fi

  echo "Creating symlink from $src to $target"
  ln -s "$src" "$target"
done
